### ISSUE TITLE
command-> param, param2, param3 should be valid EMD.

### ISSUE THREAD

**Issue by robertreppel** [Adaptech/les#3]
* TODO: 'command -> someParameter' should be valid EMD.  

The current implementation is ```command -> // someParameter```,  but it's very common to forget entering the '//'. This is not good because les and webeventstorming.com fail silently (or sometimes confusingly). Suggest that it might be better to fall forward and make both the ```command-> // parameter``` and the ```command-> parameter``` syntax valid EMD.

**Comment by markgukov** [comment]
Looks like it's already the case.
